### ISSUE TITLE
how can install it?

### ISSUE THREAD

**Issue by johnfelipe** [chaman21/DrawingTool#1]
stay alert

**Comment by johnfelipe** [comment]
felipe@cloud:~/draw$ cd
	felipe@cloud:~$ git clone https://github.com/chamanbanthia/DrawingTool.git
	Cloning into 'DrawingTool'...
	remote: Counting objects: 701, done.
	remote: Compressing objects: 100% (523/523), done.
	remote: Total 701 (delta 132), reused 699 (delta 131), pack-reused 0
	Receiving objects: 100% (701/701), 2.01 MiB | 1.93 MiB/s, done.
	Resolving deltas: 100% (132/132), done.
	Checking connectivity... done.
	felipe@cloud:~$ cd DrawingTool/
	felipe@cloud:~/DrawingTool$ npm install
	npm notice created a lockfile as package-lock.json. You should commit this file.
	npm WARN drawingtool@1.0.0 No description
	npm WARN drawingtool@1.0.0 No repository field.

	up to date in 0.368s
	felipe@cloud:~/DrawingTool$ node server.js
	Server running on 127.0.0.1:8080
	events.js:182
		  throw er; // Unhandled 'error' event
		  ^

	Error: listen EADDRINUSE :::8080
		at Object._errnoException (util.js:1022:11)
		at _exceptionWithHostPort (util.js:1045:20)
		at Server.setupListenHandle [as _listen2] (net.js:1330:14)
		at listenInCluster (net.js:1378:12)
		at Server.listen (net.js:1478:7)
		at Object.<anonymous> (/home/felipe/DrawingTool/server.js:9:8)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)
		at tryModuleLoad (module.js:470:12)
